name: CI/CD

on:
  push:
    branches:
      - features
  pull_request:
    branches:
      - '*'

jobs:

  Build:
    uses: Annamalaisaravanan/test-repo/.github/workflows/stage-template.yml@main
    with:
      Name: Build
      Enabled: true

  Test:
    uses: Annamalaisaravanan/test-repo/.github/workflows/stage-template.yml@main
    needs: Build
    with:
      Name: Test
      Enabled: startsWith(github.ref, 'refs/heads/features')


 