name: CI/CD

on:
  push:
    branches:
      - features
  pull_request:
    branches:
      - '*'

jobs:
  - template: stage-template.yml
    parameters:
      Name: Build
      Enabled: true

  - template: stage-template.yml
    parameters:
      Name: Test
      Enabled: startsWith(github.ref, 'refs/heads/features')

  - template: stage-template.yml
    parameters:
      Name: Acceptance
      Enabled: startsWith(github.ref, 'refs/heads/releases')

  - template: stage-template.yml
    parameters:
      Name: Production
      Enabled: startsWith(github.ref, 'refs/heads/releases')
