name: CI/CD

on:
  push:
    branches:
      - features
  pull_request:
    branches:
      - '*'

jobs:

  Build:
    uses: stage-template.yml
    with:
      Name: Build
      Enabled: true

  Test:
    uses: stage-template.yml
    with:
      Name: Test
      Enabled: startsWith(github.ref, 'refs/heads/features')


 