name: CI/CD 

on:
  push:
    branches:
      - features
      - releases
  pull_request:
    branches:
      - '*'

jobs:

  Build:
       if: startsWith(github.ref, 'refs/heads/features')
       runs-on: ubuntu-latest
       steps:
          - name: Checkout Repository
            uses: actions/checkout@v2

          - name: Build
            run: |
              # Add your build commands here
              echo "Building..."

  Test:
      if: startsWith(github.ref, 'refs/heads/features')
      runs-on: ubuntu-latest
      needs: Build
      steps:
          - name: Checkout Repository
            uses: actions/checkout@v2

          - name: Test
            run: |
              # Add your test commands here
              echo "Testing..."

  Staging:
      if: always() && startsWith(github.ref, 'refs/heads/releases')
      runs-on: ubuntu-latest
      needs: Test
      steps:
          - name: Checkout Repository
            uses: actions/checkout@v2
            
          - name: Acceptance
            run: |
              # Add your acceptance testing commands here
              echo "Acceptance testing..."
  
  Production:
      if: always() && startsWith(github.ref, 'refs/heads/releases') 
      runs-on: ubuntu-latest
      environment: prod
      needs: Staging
      steps:
          - name: Checkout Repository
            uses: actions/checkout@v2
            
          - name: Production
            if: startsWith(github.ref, 'refs/heads/releases')
            run: |
              # Add your production deployment commands here
              echo "Deploying to Production..."
  

           

  


 