name: CI/CD 

on:
  push:
    branches:
      - features
      - releases
  pull_request:
    branches:
      - '*'

jobs:
  Pipeline:
    runs-on: windows-latest

    env:
       
       MY_ENV_VAR: ${{ github.ref == 'refs/heads/features' && 'feature' || github.ref == 'refs/heads/releases' && 'release' || github.ref == 'refs/heads/main' && 'main' || 'hell' }}
       db_token: db-token-$MY_ENV_VAR 
         

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build
        if: startsWith(github.ref, 'refs/heads/features')
        run: |
          # Add your build commands here
          echo "Building..."

      - name: Test
        if: startsWith(github.ref, 'refs/heads/features')
        run: |
          # Add your test commands here
          echo "Testing..."
      
      - name: Acceptance
        if: startsWith(github.ref, 'refs/heads/releases')
        run: |
          # Add your acceptance testing commands here
          echo "Acceptance testing..."
      
      - name: Production
        if: startsWith(github.ref, 'refs/heads/releases')
        run: |
          # Add your production deployment commands here
          echo "Deploying to Production..."

      - name: Get Branch Name
        run: |
          
          echo "my env var: $MY_ENV_VAR"


 