trigger:
  branches:
    exclude:
      - 'main'

pr:
- '*'

pool:
  vmImage: 'windows-latest'

stages:
  - template: stage-template.yaml
    parameters:
      Name: Build
      Enabled: True

  - template: stage-template.yaml
    parameters:
      Name: Test
      Enabled: ${{ startsWith(variables['Build.SourceBranch'], 'refs/heads/features') }}

  - template: stage-template.yaml
    parameters:
      Name: Acceptance
      Enabled: ${{ startsWith(variables['Build.SourceBranch'], 'refs/heads/releases') }}

  - template: stage-template.yaml
    parameters:
      Name: Production
      Enabled: ${{ startsWith(variables['Build.SourceBranch'], 'refs/heads/releases') }}
