name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        enabled:
          - true
          - false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PowerShell
        uses: actions/setup-powershell@v1

      - name: Build
        if: matrix.enabled == 'true'
        run: |
          echo "Build Job is running. Parameter Enabled - '${{ matrix.enabled }}' "

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        enabled:
          - true
          - false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PowerShell
        uses: actions/setup-powershell@v1

      - name: Test
        if: matrix.enabled == 'true'
        run: |
          echo "Test Job is running. Parameter Enabled - '${{ matrix.enabled }}' "

  acceptance:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        enabled:
          - true
          - false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PowerShell
        uses: actions/setup-powershell@v1

      - name: Acceptance
        if: matrix.enabled == 'true'
        run: |
          echo "Acceptance Job is running. Parameter Enabled - '${{ matrix.enabled }}' "

  prod:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        enabled:
          - true
          - false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PowerShell
        uses: actions/setup-powershell@v1

      - name: Prod
        if: matrix.enabled == 'true'
        run: |
          echo "Prod Job is running. Parameter Enabled - '${{ matrix.enabled }}' "
