jobs:
  ${{ parameters.Name }}:
  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: ${{ parameters.Name }}
        if: ${{ parameters.Enabled }}
        run: |
          # Add your stage-specific commands here
          echo "${{ parameters.Name }} Job is running. Parameter Enabled - ${{ parameters.Enabled }}"
